name: Stanley-lua/CLI
description: Commandline interface wrapper for Lua.
version: 0.1
author: 
  - email: wolf2789@gmail.com
    name: Dawid Bugajski
autoload:
  - type: global
    name: CLI
    path: CLI.lua
require:
  - name: Stanley-lua/Debug
  - name: Stanley-lua/spairs
  - name: Stanley-lua/switch
