name: Wolf2789/CLI
description: Commandline interface wrapper for Lua.
version: 0.1
author: 
  - email: wolf2789@gmail.com
    name: Dawid Bugajski
autoload:
  - type: global
    name: CLI
    path: CLI.lua
require:
  - name: Wolf2789/Debug
    source: local